apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command:
    - echo
    - "Tiller required min 1 resource to be created."
    name: busybox
  restartPolicy: Never